services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres_password

  redis:
    image: redis
  
  server:
    image: krsudhir002/fib-server
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGHOST=postgres
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=postgres_password
      - PGDATABASE=postgres
  worker:
    image: krsudhir002/fib-worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  client:
    image: krsudhir002/fib-client
  nginx:
    image: krsudhir002/fib-nginx
    ports:
      - "80:80"
    restart: always

      